### ISSUE TITLE
incohérence sur trajets piéton 

### ISSUE THREAD

**Issue by kvnco** [MaisClement/Navika_App#11]
Bonjour,

Super job sur cette appli hyper prometteuse !

J'ai noté un comportement un peu surprenant sur les trajets piétons proposés. Il semble que dans certains cas il considère des alternatives avec correspondances (?) et dans ces cas-ci la durée de trajet indiquée semble sous-évaluée.
Voir un exemple avec les captures jointes

![Screenshot_20231231-111823](https://github.com/MaisClement/Navika_App/assets/2389101/0fbd10ec-29a4-408d-ae94-9118655d66d7)
![Screenshot_20231231-111846](https://github.com/MaisClement/Navika_App/assets/2389101/a74d8713-142a-4110-8990-808e09b53c4f)
![Screenshot_20231231-111910](https://github.com/MaisClement/Navika_App/assets/2389101/629a669c-a442-43d1-b5ab-bf19f48730b0)

**Comment by MaisClement** [comment]
Hello @kvnco ,

Le problème vient de l'API qui gère mal certains trajet (sections a vélo interprété comme étant piéton). La prochaine mise à jour intégre un correctif pour masquer ces trajets. Avant peut être une vraie implémentation des trajet mixte.

Bonne soirée !

**Comment by kvnco** [comment]
Ah, je comprends mieux ! Ça doit correspondre aux trajets avec VLS effectivement.
Ben du coup, quand il sera possible de les avoir. Ça sera cool aussi !

**Comment by MaisClement** [comment]
Hello @kvnco,

Ce problème a été corrigé avec la dernière mise à jour. Je vais créer une nouvelle issue pour l’implémentation des trajet mixte.

Merci !

**Comment by kvnco** [comment]
Vu et déjà testé. ;)
Bravo et merci
