### ISSUE TITLE
L'appli ne démarre pas

### ISSUE THREAD

**Issue by Rathmox** [MaisClement/Navika_App#12]
L'appli reste bloquée sur le logo et ne continue jamais.

Appareil: Google Pixel 7
CPU: arm64-v8a only
OS: GrapheneOS

**Comment by MaisClement** [comment]
Hello @Rathmox,

La cause la plus probable est l'absence des services Google Play sur GrapheneOS (requis pour les notifications). 
Je vais voir ce que je peux faire (et vérifier mon hypothèse)

Bonne soirée !

**Comment by Rathmox** [comment]
J'ai l'impression que c'est du aux notifications qui ne peuvent pas s'ajouter aux google play services. Car en installant les play services, elle me demande l'accès aux notifications, puis peut démarrer

**Comment by MaisClement** [comment]
On avance ! Tu sais me dire si les notifications fonctionnent bien ?

Tu peux tester en créant une alerte trafic, si tu reçois une notif immédiatement après c'est que ça fonctionne.

**Comment by Rathmox** [comment]
J'ai essayé.

Avec Google Play: pas de notification

Sans Google Play: impossible de définir l'alerte: "récupération des informations impossible"

**Comment by Rathmox** [comment]
un peu en retard mais réglé
