### ISSUE TITLE
Actualiser un trajet après le passage d'un train ne décale pas le trajet

### ISSUE THREAD

**Issue by Kalytis** [MaisClement/Navika_App#17]
![Screenshot_20240106-093608_Navika](https://github.com/MaisClement/Navika_App/assets/31107370/bf03642d-d15d-4505-b23e-2a0b3276aa9e)

En théorie, refresh la liste des itinéraires proposés après le passage des trains devrait décaler les itinéraires pour les aligner sur le train suivant. Là, le train passé reste.

**Comment by Kalytis** [comment]
@MaisClement #17 et #18 me semblaient plutôt être des bugs AMHA !

**Comment by MaisClement** [comment]
Hello @Kalytis, c'est corrigé dans la dernière màj !
