### ISSUE TITLE
Suggestion : Cliquer sur un point d'intérêt sur la carte, ou appuyer longuement, pour sélectionner la destination

### ISSUE THREAD

**Issue by Kalytis** [MaisClement/Navika_App#26]
Ça serait pratique de pouvoir choisir les points d'adresse directement sur la carte.

**Comment by MaisClement** [comment]
Oh, bonne idée ! Je vais voir pour ajouter ça !

**Comment by Kalytis** [comment]
Je me demandais sur quoi était basé ton fond de carte, on dirait du Mappy, comme sur les applis officielles ?

**Comment by MaisClement** [comment]
La carte c'est HERE

**Comment by Kalytis** [comment]
T'as pas envie/tu peux pas passer à OpenStreetMap ?

**Comment by Kalytis** [comment]
Ohhhhh le "À proximité" pour connaître le meilleur arrêt de transport il est in-cro-yable 🔥

Pour le design d'OSM y'a différents fonds de carte, moi je sais que j'aime bien OSM Sunny. Le design par défaut est pas ouf. Mais ça permet d'avoir un max de points d'intérêt à jour, et même intégrer des infos sur eux (horaires, site web...).

P'tet https://github.com/systemed/tilemaker pourrait aider ?

**Comment by MaisClement** [comment]
Pour OSM, je me suis jamais vraiment posé la question. J'ai pris here (en hésitant avec GGmaps) parce que j'avais déjà fait quelques projets scolaires avec.

Il faut voir a quelle point c'est simple de basculer sur OSM, parce que ça nécessiterait de refaire les contrôleurs. Je pourrais regarder, mais c'est pas ma priorités 😅

**Comment by Kalytis** [comment]
En tout cas la feature a l'air incroyable, peut-être des ajustements à faire à l'usage, mais merci mille fois pour ton taf

**Comment by MaisClement** [comment]
Disponible dans les mise à jour d'aujourd'hui (sur le playstore, pas encore sur github)

**Comment by Kalytis** [comment]
Insaneeeeeee merci beaucoup Clément 🙏 j'attends la version Github donc (voire F-droid, j'espère !)

**Comment by MaisClement** [comment]
Re, C'est également disponible sur Github !

Faut je regarde pour F-droid 😅
