### ISSUE TITLE
Aucun train vers le nord

### ISSUE THREAD

**Issue by tmarti2** [MaisClement/Navika_App#27]
Hello,

J'ai cherché les horaires de la ligne B depuis Bourg-la-Reine et l'appli ne me montre que les trains vers le sud (cf. Screenshots). Je confirme qu'il ya des trains vers Gare du Nord (un dans 5 minutes au moment du screen et d'autres qui suivent). Le calcule d'itinéraire fonctionne correctement, c'est uniquement l'onglet horaire (et la page d'accueil). Ça fonctionne correctement pour la gare d'Orsay Ville ou Massy-Palaiseau.
![Screenshot_2024-01-20-14-02-32-75_415b62526af6dd3c0fd1f7de546c4c53](https://github.com/MaisClement/Navika_App/assets/32908972/d6dbe71e-6623-4ff1-9997-63d06ba3e0ff)

Edit: les horaires en direct ne prennent pas en compte le retard du rer AURA75 qui n'était pas affiché, mais je sais pas si c'est lié (il a 3 minutes de retard constant par rapport aux horaires officielles)

Merci !

**Comment by MaisClement** [comment]
Hello, malheureusement ces infos sont tiré directement des API. Je vais quand même regarder s'il ne s'agit pas d'une mauvaise lecture/interprétation des données 🤷

**Comment by tmarti2** [comment]
J'ai peut-être une théorie : j'avais pas vu mais il ya des travaux qui ont pour conséquences, entre autres, que les RER B soient terminus Gare du Nord avec une correspondance à faire pour aller plus au nord. Peut-être que ça a cassé quelque chose. Normalement il y aura la même chose ce weekend du 27-28 donc je surveillerai. Si c'est ça a priori c'est pas trop gênant puisque temporaire.

**Comment by MaisClement** [comment]
C'est peut-être une explication. J'ai pas eu le temps de regarder plus en détails. Peut être que les données sont mal interprèter ou autre 😅. J'essaie de voir ça ce week-end

**Comment by tmarti2** [comment]
J'ai totalement oublié d'update : j'ai pas eu ce problème depuis, je ferme l'issue du coup.
