### ISSUE TITLE
Improvement : Mauvaise visibilité de la ligne de trajet lors de la navigation

### ISSUE THREAD

**Issue by Kalytis** [MaisClement/Navika_App#33]
![Screenshot_20240127-161839_Navika](https://github.com/MaisClement/Navika_App/assets/31107370/af49ef59-547a-4819-a57b-ea684680bf5f)
![Screenshot_20240127-161842_Navika](https://github.com/MaisClement/Navika_App/assets/31107370/3b2014c7-2276-43a8-8ea5-0b5077d6721b)

En fonction de l'orientation c'est pas super visible je trouve

**Comment by MaisClement** [comment]
J'ai légèrement augmenter l’épaisseur de la ligne et surtout, elle est change de couleur selon le thème

![Screenshot_20240127-170610](https://github.com/MaisClement/Navika_App/assets/43115848/d968ec22-2b70-46d3-9ac8-12f6e42d2cd8)
![Screenshot_20240127-170649](https://github.com/MaisClement/Navika_App/assets/43115848/e67dd5d1-44c1-4b2e-9d0d-46c02d7f839c)

Il faudrait peut être que je retire la 3D des bâtiment dans ce cas ? Dit moi ce que tu en pense 😅

**Comment by Kalytis** [comment]
C'est carrément mieux !! La 3d gêne pas, il faut juste pas que les bâtiments obscursissent trop la ligne, amha

**Comment by MaisClement** [comment]
Disponible dans la dernière version !
