### ISSUE TITLE
Rechargement des résultats de recherche

### ISSUE THREAD

**Issue by benjamin-voisin** [MaisClement/Navika_App#49]
Après avoir fait une recherche d'itinéraire, quand on clique sur un résultat pour regarder s'il nous plait, puis qu'on reviens à l'écran des résultats, il semble que l'application recherche à nouveau les itinéraires, au lieu de simplement réafficher la page précédente.
C'est particulièrement désagréable quand on a une connction limité.

J'ai l'impression que ça peut se changer sans trop de difficulté, et même si j'ai jamais fait ce genre de développement je peux essayer de m'en occuper (j'aime beaucoup ce projet et j'aimerais m'y impliquer)

(je suis pas sûr du label à mettre, c'est plutôt un "unwanted behaviour")

**Comment by MaisClement** [comment]
Hello @benjamin-voisin, c’est effectivement pas bien difficile à corriger / modifier, tu peut regarder la pull request #50 
Cette correction va faire partie de la prochaine mise à jour.

Enfin, ravi de voir que le projet t’intéresse !
