### ISSUE TITLE
Certaines lignes de train sont dupliquées ou vides sans raison

### ISSUE THREAD

**Issue by Rathmox** [MaisClement/Navika_App#66]
Je me doute bien que les API SNCF ne sont pas bien nettoyées et que des vestiges restent (ces noms de lignes sont même plus utilisés, n'empêche qu'ils sont pratiques), mais il y a-t-il une explication plus précise et un moyen de les masquer ?

![Screenshot_20240725-165747](https://github.com/user-attachments/assets/417b45ba-465d-47ba-982f-98c7ef0a0d99)

**Comment by MaisClement** [comment]
Hello,
Malheureusement, les données de la SNCF sont regroupé comme cela. Dans les réglages de l'application tu peut changer cet affichage.
Options > Tableau des départs > Dégroupé
![image](https://github.com/user-attachments/assets/709902da-9d87-4366-b136-38207d51352d).

**Comment by Rathmox** [comment]
j'avais pas vu, mais je les préfère groupées perso
